### PR TITLE
Doc fixes 

### PR DESCRIPTION
**Pull request by MonadicT**
Fixed type check errors in sample code.

### CODE REVIEW

**Comment by hsyl20** [comment]
Thanks!

I hope we'll be able to get rid of the `Functor (VariantF xs)` constraints in the future with https://homepage.cs.uiowa.edu/~jgmorrs/pubs/jones-popl2020-partial.pdf

**Comment by MonadicT** [comment]
Thank you for the quick response. Also, thanks for the pointer. Will take a
look.

**Comment by hsyl20** [comment]
I haven't read the paper yet, only watched the corresponding talk https://www.youtube.com/watch?v=rqmCwpRXT_E

**Comment by MonadicT** [comment]
Thanks for the YT link and just finished watching it :)

Yea, it would be nice if and when this lands in GHC.

**Pull request merged**
